version: '3.8'

services:
  wisdomweb-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=production
    volumes:
      # 如果需要挂载nginx日志
      - ./logs/nginx:/var/log/nginx
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 开发环境服务（可选）
  wisdomweb-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    profiles:
      - dev
