apiVersion: v1
kind: Service
metadata:
  name: search-engine
  namespace: prod
  labels:
    app: search-engine
spec:
  selector:
    app: search-engine
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: ClusterIP