apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-engine
  namespace: prod
  labels:
    app: search-engine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: search-engine
  template:
    metadata:
      labels:
        app: search-engine
    spec:
      containers:
      - name: search-engine
        image: cpmores/search-server:v1.0
        volumeMounts:
        - name: efs-storage
          mountPath: /data
        ports:
        - containerPort: 3001
        env:
        - name: STORAGE_HOST
          value: storage.prod.svc.cluster.local  
        - name: STORAGE_PORT
          value: "27017"  
        resources:
          requests:
            cpu: "0.5"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"

      volumes:
      - name: efs-storage
        persistentVolumeClaim:
          claimName: storage-pvc
