apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-engine
  namespace: prod
  labels:
    app: search-engine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: search-engine
  template:
    metadata:
      labels:
        app: search-engine
    spec:
      containers:
      - name: search-engine
        image: cpmores/search-server:v1.0
        ports:
        - containerPort: 3001
        env:
        - name: STORAGE_HOST
          value: storage.prod.svc.cluster.local  # 你的 storage 服务地址
        - name: STORAGE_PORT
          value: "27017"  # 根据实际端口修改
        resources:
          requests:
            cpu: "0.5"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 20

        volumeMounts:
          - name: shared-storage
            mountPath: /app/storage

      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: storage-pvc