apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: prod
spec:
  type: ClusterIP
  clusterIP: None  # Headless Service for StatefulSet
  selector:
    app: database
  ports:
  - port: 3306
    name: mariadb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: prod
spec:
  serviceName: database
  replicas: 3
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.11  # 你可以换成合适版本
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: root-password
        - name: MARIADB_DATABASE
          value: "userdb"
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - "-u"
            - root
            - "-p$(MARIADB_ROOT_PASSWORD)"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - mysql
            - "-u"
            - root
            - "-p$(MARIADB_ROOT_PASSWORD)"
            - "-e"
            - "SELECT 1"
  volumeClaimTemplates:
  - metadata:
      name: mariadb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: ebs-gp3-encrypted
      resources:
        requests:
          storage: 50Gi
