# 4. 数据库Secrets
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  namespace: prod
type: Opaque
data:
  root-password: <base64-root-password>
  username: V2ViU2VhcmNo
  password: V2ViU2VhcmNoMTIzIQ==
