apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-index
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-index
  template:
    metadata:
      labels:
        app: load-index
    spec:
      containers:
      - name: load-index
        image: cpmores/load_index:v1.0  
        ports:
        - containerPort: 3004
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: storage-pv
          mountPath: /app/storage  # 根据你的应用调整路径
      volumes:
      - name: storage-pv
        persistentVolumeClaim:
          claimName: storage-pvc  # 请确认 PVC 名称是否正确
