apiVersion: v1
kind: Service
metadata:
  name: prefix-trie-server
  namespace: prod
spec:
  selector:
    app: prefix-trie-server
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
  type: ClusterIP