apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wisdomweb-ingress
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: wisdomweb.local
      http:
        paths:
          # 前端服务（根路径）
          - path: /()(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

          # 后端Web
          - path: /backend(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080

          # 搜索引擎 search-engine
          - path: /search-engine(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: search-engine
                port:
                  number: 3001

          # 爬虫 crawler
          - path: /crawler(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: crawler
                port:
                  number: 3000

          # 关键词补全 keyword-service
          - path: /keyword-service(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: keyword-service
                port:
                  number: 5000

          # 前缀树 prefix-trie-server
          - path: /prefix-trie-server(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: prefix-trie-server
                port:
                  number: 3002

          # AI Agent 服务
          - path: /ai-agent(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: ai-agent
                port:
                  number: 3003

          #词云服务
          - path: /load-index(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: load-index
                port:
                  number: 3004