# 2. AI Agent Service
apiVersion: v1
kind: Service
metadata:
  name: ai-agent
  namespace: prod
spec:
  selector:
    app: ai-agent
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  type: ClusterIP
