apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-pv
  namespace: prod
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/storage  # 控制节点上的物理路径，开发环境可用