# Backend ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: prod
data:
  SPRING_DATASOURCE_URL: "jdbc:mariadb://mariadb:3306/WebSearch"
  SPRING_DATASOURCE_USERNAME: "WebSearch"
  SPRING_DATASOURCE_PASSWORD: "WebSearch123!"
  SEARCHENGINE_URL: "http://search-engine:3001/search"
  CRAWLER_URL: "http://crawler:3000"
  SPRING_PROFILES_ACTIVE: "production"
  JAVA_OPTS: "-Xms256m -Xmx512m"