# Backend ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: prod
data:
  SPRING_DATASOURCE_URL: "jdbc:mariadb://widsomweb-db.c8m5rwwx8dws.us-east-1.rds.amazonaws.com:3306/WebSearch"
  SEARCHENGINE_URL: "http://search-engine:3001/search"
  CRAWLER_URL: "http://crawler:3000"
  SPRING_PROFILES_ACTIVE: "production"
  JAVA_OPTS: "-Xms256m -Xmx512m"
