---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
  namespace: prod
  labels:
    app: crawler
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: crawler
  template:
    metadata:
      labels:
        app: crawler
    spec:
      containers:
      - name: crawler
        image: cpmores/storage-server:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000  
        volumeMounts:
        - name: efs-storage
          mountPath: /data  
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.5"
          limits:
            memory: "512Mi"
            cpu: "1"
       
      volumes:
      - name: efs-storage
        persistentVolumeClaim:
          claimName: storage-pvc


