---
apiVersion: v1
kind: Service
metadata:
  name: crawler
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: crawler
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000